version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm i -g serverless
      - pip install --upgrade pip
      - pip install --upgrade awscli
  build:
    commands:
      - serverless login
      - sls deploy -s dev --verbose
      - aws s3 sync s3://maks-api-dev
